-- CREATING A TABLE ON NETFLIX PROJECT
CREATE TABLE NETFLIX
( show_id VARCHAR(10),
  type VARCHAR(10),
  title VARCHAR(115),
  director VARCHAR(220),
  casts VARCHAR(780),	
  country	VARCHAR(130),
  date_added VARCHAR(20),
  release_year INT,
  rating VARCHAR(11),
  duration VARCHAR(11),
  listed_in VARCHAR(80),
  descriptin VARCHAR(250)
   )
SELECT * FROM NETFLIX

SELECT COUNT (*) AS 
TOTAL_CONTENT
FROM NETFLIX 

SELECT DISTINCT TYPE 
FROM NETFLIX 

SELECT * FROM NETFLIX

-- BUSINESS PROBLEMS
1.-- COUNT THE NUMBER OF MOVIES VS TV SHOW
SELECT TYPE,COUNT(*)
AS TOTAL_CONTENT
FROM NETFLIX 
GROUP BY TYPE

2.-- FIND THE MOST COMMON RATING FOR MOVIES AND TV SHOWS
SELECT TYPE,
       RATING
FROM
(SELECT TYPE,
      RATING,
	  COUNT(*),
	  RANK() OVER(PARTITION 
	  BY TYPE ORDER BY COUNT(*) DESC)
	  AS RANKING
FROM NETFLIX
GROUP BY 1,2
) 
AS T1
WHERE RANKING=1
ORDER BY TYPE DESC

3.-- LIST ALL MOVIES RELEASED IN 2020
SELECT * FROM NETFLIX
WHERE TYPE='Movie'
       AND
      RELEASE_YEAR = 2020


4.-- FIND THE TOP 5 COUNTRIES WITH THE MOST CONTENT ON NETFLIX

SELECT UNNEST(STRING_TO_ARRAY(COUNTRY,','))AS COUNTRY ,
COUNT(SHOW_ID)  AS TOTAL_CONTENT
FROM NETFLIX 
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5

SELECT 
UNNEST(STRING_TO_ARRAY(COUNTRY,','))AS NEW_COUNTRY
FROM NETFLIX 

5.-- IDENTIFY THE LONGEST MOVIE
SELECT * 
FROM NETFLIX
WHERE TYPE = 'Movie'
AND DURATION=(SELECT MAX(DURATION)FROM NETFLIX)


6.-- FIND CONTENT ADDED IN THE LAST 5 YEARS
SELECT *
FROM NETFLIX
WHERE TO_DATE
(DATE_ADDED,'MONTH DD YYYY') >= CURRENT_DATE - INTERVAL '5 YEARS'

7.-- FIND ALL THE MOVIES AND TV SHOWS BY DIRECTOR 'RAJIV CHILAKA'
SELECT TYPE,
       TITLE,
        DIRECTOR
FROM NETFLIX 
WHERE DIRECTOR ILIKE '%Rajiv Chilaka%'

8.-- LIST ALL TV SHOWS WITH MORE THAN 5 SEASONS

SELECT *
FROM NETFLIX
WHERE TYPE = 'TV Show'
AND
SPLIT_PART(DURATION,' ',1)::NUMERIC > 5 

9.-- COUNT THE NUMBER OF CONTENT ITEMS IN EACH GENRE
SELECT
	  UNNEST (STRING_TO_ARRAY(LISTED_IN,',')) AS GENRE,
	  COUNT(SHOW_ID) AS TOTAL_CONTENT
FROM NETFLIX
GROUP BY 1
10.-- FIND EACH YEAR AND THE AVERAGE NUMBERS OF CONTENT RELEASE BY INDIA ON NETFLIX.RETURN TOP 5 YEAR WITH THE HIGHEST AVG CONTENT RELEASE
SELECT
   EXTRACT (YEAR FROM TO_DATE(DATE_ADDED,'MONTH DD,YYYY')) AS YEAR,
   COUNT
   (*) AS YEARLY_CONTENT,
   ROUND(COUNT(*)::NUMERIC/(SELECT COUNT (*) FROM NETFLIX WHERE COUNTRY = 'India')::NUMERIC* 100 ,2)AS AVG_CONTENT_PER_YEAR
   FROM NETFLIX
   WHERE COUNTRY='India'
   GROUP BY 1
   

11.-- LIST ALL MOVIES THAT ARE DOCUMENTARIES
SELECT *
FROM NETFLIX
WHERE TYPE ='Movie'
AND
LISTED_IN ILIKE '%Documentaries%'

12.-- FIND ALL CONTENT WITHOUT A DIRECTOR
SELECT * FROM NETFLIX 
WHERE DIRECTOR IS NULL

13.-- FIND HOW MANY MOVIES ACTOR 'Salman Khan' appeared in the last 10 years
SELECT * FROM NETFLIX
WHERE TYPE = 'Movie'
AND CASTS ILIKE '%Salman Khan%'
AND RELEASE_YEAR >EXTRACT(YEAR FROM CURRENT_DATE)-10

14.-- FIND THE TOP 10 ACTORS WHO HAVE APPEARED IN THE HIGHEST NUMBER OF MOVIES PRODUCED  IN INDIA
SELECT UNNEST (STRING_TO_ARRAY(CASTS,','))
AS ACTORS,COUNT(*) AS TOTAL_CONTENT
FROM NETFLIX 
WHERE COUNTRY ILIKE  '%India%'
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10

15.-- CATEGORISE THE CONTENT BASED ON THE PRESENCE OF KEYWORDS 'KILL' AND 'VIOLENCE' IN THE DESCRIPTION FIELD
-- LABEL CONTENT CONTAINING THESE WORDS AS 'BAD'AND ALL OTHER CONTENT AS 'GOOD'.COUNT HOW MANY ITEMS FALL INTO EACH CATEGORY

WITH NEW_TABLE AS
(SELECT *,
        CASE
		WHEN
		    DESCRIPTIN ILIKE '%Kill%'
                  OR
           DESCRIPTIN ILIKE '%Violence%'
           THEN 'Bad_Content'
		   ELSE 'Good_content'
END CATEGORY        
FROM NETFLIX)
SELECT CATEGORY,
COUNT(*) AS TOTAL_CONTENT
FROM NEW_TABLE
GROUP BY 1












